version: '3.8'
services:
  trading:
    build: .
    volumes:
      - .:/src
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
